import type { Metadata } from "next"
import Link from "next/link"
import { ThemeToggle } from "@/components/theme-toggle"

export const metadata: Metadata = {
  title: "Privacy Policy — EpubAnything",
  description: "Privacy policy for EpubAnything. We collect minimal data and never sell it.",
  alternates: {
    canonical: "https://epubanything.site/privacy",
  },
  robots: { index: true, follow: true },
}

const SECTIONS = [
  {
    heading: "What we collect",
    body: (
      <>
        <p>
          When you convert a URL without signing in, we collect nothing. No IP address, no
          cookies, no analytics.
        </p>
        <p>
          When you sign in with Google, we receive your <strong>name</strong> and{" "}
          <strong>email address</strong> from Google and store them in our database to identify
          your account and credit balance.
        </p>
        <p>
          When you purchase credits via PayPal, PayPal processes the payment directly. We
          receive only a confirmation and record the resulting credit balance against your
          account. We do not store card numbers or PayPal credentials.
        </p>
      </>
    ),
  },
  {
    heading: "How we use your data",
    body: (
      <p>
        Your name and email are used solely to authenticate you and associate your credit
        balance with your account. We do not use them for marketing, profiling, or any other
        purpose.
      </p>
    ),
  },
  {
    heading: "Converted files",
    body: (
      <p>
        EPUB files generated by EpubAnything are stored temporarily on Cloudflare R2. Download
        links expire after <strong>24 hours</strong>, after which the file is no longer
        accessible. We do not read, index, or share the content of converted files.
      </p>
    ),
  },
  {
    heading: "Third-party services",
    body: (
      <ul className="list-disc list-inside space-y-1">
        <li>
          <strong>Google OAuth</strong> — handles sign-in. Subject to{" "}
          <a
            href="https://policies.google.com/privacy"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: "var(--accent)" }}
            className="underline"
          >
            Google's Privacy Policy
          </a>
          .
        </li>
        <li>
          <strong>PayPal</strong> — handles payment. Subject to{" "}
          <a
            href="https://www.paypal.com/us/legalhub/privacy-full"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: "var(--accent)" }}
            className="underline"
          >
            PayPal's Privacy Policy
          </a>
          .
        </li>
        <li>
          <strong>Cloudflare R2</strong> — stores converted files for up to 24 hours.
        </li>
      </ul>
    ),
  },
  {
    heading: "Data sharing",
    body: (
      <p>
        We do not sell, rent, or share your personal data with any third party beyond the
        services listed above, which are necessary to operate EpubAnything.
      </p>
    ),
  },
  {
    heading: "Your rights",
    body: (
      <p>
        You may request deletion of your account and associated data at any time by emailing{" "}
        <a
          href="mailto:hanguk1006@gmail.com"
          style={{ color: "var(--accent)" }}
          className="underline"
        >
          hanguk1006@gmail.com
        </a>
        . We will process the request within 7 days.
      </p>
    ),
  },
  {
    heading: "Changes",
    body: (
      <p>
        If we make material changes to this policy, we will update the date below. Continued
        use of EpubAnything after changes constitutes acceptance of the updated policy.
      </p>
    ),
  },
]

export default function PrivacyPage() {
  return (
    <main className="min-h-screen flex flex-col items-center px-6 py-16">
      <ThemeToggle />
      <div className="w-full max-w-xl">
        <header className="text-center mb-10">
          <Link href="/" className="ornament hover:opacity-100 transition-opacity" style={{ color: "var(--accent)" }}>
            ← EpubAnything
          </Link>
          <div className="title-rule" />
          <h1 className="display-title">Privacy Policy</h1>
          <div className="title-rule" />
          <p className="body-text mt-3">Last updated: May 2026</p>
        </header>

        <div className="space-y-10">
          {SECTIONS.map((section) => (
            <section key={section.heading}>
              <h2 className="faq-q mb-3">{section.heading}</h2>
              <div className="body-text space-y-3">{section.body}</div>
            </section>
          ))}
        </div>

        <footer className="mt-16 text-center">
          <div className="title-rule mb-6" />
          <p className="body-text">
            Questions?{" "}
            <a
              href="mailto:hanguk1006@gmail.com"
              style={{ color: "var(--accent)" }}
              className="underline"
            >
              hanguk1006@gmail.com
            </a>
          </p>
          <p className="body-text mt-4">
            <Link href="/terms" style={{ color: "var(--accent)" }} className="underline">
              Terms of Service
            </Link>
          </p>
        </footer>
      </div>
    </main>
  )
}
